# Jekyll workshop-template evanwill
# https://github.com/evanwill/workshop-template
# based on minima theme https://github.com/jekyll/minima

# Notes: 
# - pages with "nav: true" in front matter will be in header nav
# - figure include for centered images, put file in images directory and use: {% include figure.html img="my-cat.jpg" alt="cat" caption="My cat" width="50%" %}

# Site settings
# title appears in the header
title: CogSci 2024 Workshop on Psychometrics
# description and keywords for meta tags
description: "2024 Cognitive Science Workshop on Psychometrics "
keywords: "theory development, psychometrics, measurement, individual differences"

# author settings for cc-by, appears in the footer
author: George Kachergis, Alvin Wei-Ming Tan, and Michael C. Frank
pub_year: 2024
github_username: kachergis

# add the full url for the github repository
repo: "https://github.com/kachergis/psychometrics-workshop"

# site urls
# add the url for the domain,
# on gh-pages follow the pattern: https://kachergis.github.io
url: "https://psychometrics-workshop.github.io"
# add subsection of the domain,
# on gh-pages this is /psychometrics-workshop
baseurl: ""

# add google analytics if desired (optional)
# if blank, it will be ignored
# use JEKYLL_ENV=production on build command
google-analytics-id: 

# defaults (to simplify front matter)
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Build settings
markdown: kramdown
